In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup as BS
import numpy as np
import re
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import seaborn as sns
import urllib.robotparser as urobot
from urllib.request import urlopen
from pylab import rcParams
import csv

%matplotlib inline

In [2]:
#Load list_of_champs table 

df1 = pd.read_csv('../data/list_of_champs.csv')

df1.head()

,Weight Class,Name,Sex,Record,Fighting Style,Country,Nickname,Title Holder
0,Heavyweight\n,Mark Coleman\n,Male,16-10,Wrestling,USA,The Hammer,Former
1,Heavyweight\n,Maurice Smith\n,Male,14-14,Kickboxing,USA,Mo,Former
2,Heavyweight\n,Randy Couture\n,Male,19-11,Wrestling,USA,The Natural,Former
3,Heavyweight\n,Bas Rutten\n,Male,28-4,"Kickboxing, Wrestling",Netherlands,El Guapo (The Handsome One),Former
4,Heavyweight\n,Kevin Randleman\n,Male,17-16,"Wrestling, Boxing",USA,The Monster,Former

In [3]:
df1.info

<bound method DataFrame.info of       Weight Class                  Name     Sex  Record  \
0    Heavyweight\n        Mark Coleman\n    Male   16-10
1    Heavyweight\n       Maurice Smith\n    Male   14-14
2    Heavyweight\n       Randy Couture\n    Male   19-11
3    Heavyweight\n          Bas Rutten\n    Male   28-4
4    Heavyweight\n     Kevin Randleman\n    Male   17-16
..             ...                   ...     ...     ...
114    Strawweight         Carla Esparza  Female    17-6
115    Strawweight  Joanna Jedrzejczyk\n  Female    16-4
116    Strawweight        Rose Namajunas  Female     9-4
117    Strawweight       Jessica Andrade  Female    21-8
118    Strawweight           Zhang Weili  Female    21-1

                   Fighting Style      Country                     Nickname  \
0                       Wrestling          USA                   The Hammer
1                      Kickboxing          USA                           Mo
2                       Wrestling          USA                  The Natural
3           Kickboxing, Wrestling  Netherlands  El Guapo (The Handsome One)
4               Wrestling, Boxing          USA                  The Monster
..                            ...          ...                          ...
114          Wrestling, Jiu-Jitsu          USA               Cookie Monster
115         Muay thai, Kickboxing       Poland                      Unknown
116  Jiu-Jitsu, Karate, Taekwondo          USA                    Thug Rose
117  Jiu-Jitsu, Boxing, Muat thai       Brazil                  Bate Estaca
118                     Jiu-Jitsu        China                       Magnum

    Title Holder
0         Former
1         Former
2         Former
3         Former
4         Former
..           ...
114       Former
115       Former
116       Former
117       Former
118      Current

[119 rows x 8 columns]>

In [4]:
# Remove "\n" on both weight class, name columns

df1[' Weight Class'] = df1[' Weight Class'].str.strip()
df1.head()

,Weight Class,Name,Sex,Record,Fighting Style,Country,Nickname,Title Holder
0,Heavyweight,Mark Coleman\n,Male,16-10,Wrestling,USA,The Hammer,Former
1,Heavyweight,Maurice Smith\n,Male,14-14,Kickboxing,USA,Mo,Former
2,Heavyweight,Randy Couture\n,Male,19-11,Wrestling,USA,The Natural,Former
3,Heavyweight,Bas Rutten\n,Male,28-4,"Kickboxing, Wrestling",Netherlands,El Guapo (The Handsome One),Former
4,Heavyweight,Kevin Randleman\n,Male,17-16,"Wrestling, Boxing",USA,The Monster,Former

In [5]:
df1[' Name'] = df1[' Name'].str.strip()
df1.head()

,Weight Class,Name,Sex,Record,Fighting Style,Country,Nickname,Title Holder
0,Heavyweight,Mark Coleman,Male,16-10,Wrestling,USA,The Hammer,Former
1,Heavyweight,Maurice Smith,Male,14-14,Kickboxing,USA,Mo,Former
2,Heavyweight,Randy Couture,Male,19-11,Wrestling,USA,The Natural,Former
3,Heavyweight,Bas Rutten,Male,28-4,"Kickboxing, Wrestling",Netherlands,El Guapo (The Handsome One),Former
4,Heavyweight,Kevin Randleman,Male,17-16,"Wrestling, Boxing",USA,The Monster,Former

In [6]:
#Count of current and former champs

df2 = df1.groupby(['Title Holder']).agg(['count'])
df2 = df1.drop([' Name','Sex','Fighting Style','Country','Nickname'], axis=1)
df2

     Weight Class  Record Title Holder
0     Heavyweight   16-10       Former
1     Heavyweight   14-14       Former
2     Heavyweight   19-11       Former
3     Heavyweight   28-4        Former
4     Heavyweight   17-16       Former
..            ...     ...          ...
114   Strawweight    17-6       Former
115   Strawweight    16-4       Former
116   Strawweight     9-4       Former
117   Strawweight    21-8       Former
118   Strawweight    21-1      Current

[119 rows x 3 columns]

In [7]:
Current_champs = df1[df1['Title Holder'] == 'Current']
Current_champs.head(10)

,Weight Class,Name,Sex,Record,Fighting Style,Country,Nickname,Title Holder
23,Heavyweight,Stipe Miocic,Male,20-3,Wresling,USA,Unknown,Current
25,Heavyweight,Stipe Miocic,Male,20-3,Wresling,USA,Unknown,Current
42,Light Heavyweight,Jan Blachowicz,Male,27-8,Jiu-Jitsu,Poland,Prince of Cieszyn,Current
54,Middleweight,Israel Adesanya (interim title holder),Male,20-0,"Kickboxing, Boxing",Nigeria,The Last Stylebender,Current
55,Middleweight,Israel Adesanya,Male,20-0,"Kickboxing, Boxing",NaN,The Last Stylebender,Current
70,Welterweight,Kamaru Usman,Male,17-1,Wrestling,Nigeria,The Nigerian Nightmare,Current
81,Lightweight,Khabib Nurmagomedov,Male,29-0,Sambo,Russia,The Eagle,Current
84,Lightweight,Khabib Nurmagomedov,Male,29-0,Sambo,Russia,The Eagle,Current
101,Bantamweight,Petr Yan,Male,15-1,"Boxing, Muay thai",Russia,No Mercy,Current
104,Flyweight,Deiveson Figueiredo,Male,20-1,Jiu-Jitsu,Brazil,Daico,Current